In [3]:
import sys
import numpy as np
import matplotlib as plt
import pandas as pd
import math
import random 

In [4]:
df= pd.read_csv("train.csv",header=0)
print(df.columns.values)
pd.set_option('display.max_columns', None)
df1 = df[['Survived', 'Pclass', 'Age', 'Sex','SibSp','Parch','Fare']]
#df1['Sex'] = df1['Sex'].astype('category')
df1['Sex']=df1['Sex'].astype('category').cat.codes
df1=df1.dropna()

['PassengerId' 'Survived' 'Pclass' 'Name' 'Sex' 'Age' 'SibSp' 'Parch'
 'Ticket' 'Fare' 'Cabin' 'Embarked']


/var/folders/kq/3v19hhb53m9dfk3n1w8rgqbc0000gn/T/ipykernel_3297/3701819441.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Sex']=df1['Sex'].astype('category').cat.codes


In [7]:
x_train=df1[['Pclass', 'Age', 'Sex','SibSp','Parch','Fare']]
y_train=df1[['Survived']]

In [9]:

x_train=x_train.copy().to_numpy()
Y=y_train.copy().to_numpy()

In [11]:
def initialize_weights(no_of_columns):
    return np.arange(no_of_columns)
    

In [13]:
print(initialize_weights(6))

[0 1 2 3 4 5]


In [15]:
def compute_linear(x,w,b):
    return np.dot(x,w)+b

In [17]:
x=np.random.rand(3,6)
w=initialize_weights(6)
b=random.randint(1,10)
y=np.array([0,1,0])
a=0.01

In [18]:
print(w,'\n',x,'\n',b)

[0 1 2 3 4 5] 
 [[0.30504808 0.4816866  0.5706137  0.1734728  0.05114651 0.03481669]
 [0.57070618 0.37419684 0.42297634 0.81842549 0.32542393 0.80247378]
 [0.95065393 0.46739443 0.59557256 0.221938   0.94807255 0.33543043]] 
 3


In [20]:
0.885493+(2*0.60896795)+(3*0.51176963)+(4*0.44391879)+(5*0.09053383)

5.8670821

In [117]:
compute_linear(x,w,b)

array([22.96536195, 32.71731069, 83.48465864])

In [152]:
def compute_logistic(x,w,b):
    print("X:",x)
    print("w:",w)
    print("b:",b)
    print("Compute_linear :",compute_linear(x,w,b))
    print("Math :",math.e**(-compute_linear(x,w,b)))
    print("math+1:",1+(math.e**(-compute_linear(x,w,b))))
    print("Final :", 1/(1+(math.e**(-compute_linear(x,w,b)))))
    return 1/(1+(math.e**(-compute_linear(x,w,b))))
    

In [154]:
compute_logistic(x,w,b)

X: [[0.25905518 0.32779069 0.53856307 0.43586175 0.34719479 0.46032131]
 [0.41884025 0.04570232 0.64506201 0.94240861 0.28457244 0.22646675]
 [0.5775232  0.13003756 0.93154279 0.24364431 0.44417751 0.66790269]]
w: [0 1 2 3 4 5]
b: 5
Compute_linear : [11.40288779 11.43367568 12.84027957]
Math : [1.11632013e-05 1.08247467e-05 2.65177966e-06]
math+1: [1.00001116 1.00001082 1.00000265]
Final : [0.99998884 0.99998918 0.99999735]


array([0.99998884, 0.99998918, 0.99999735])

In [177]:
def compute_logistics_loss(x,y,w,b):
    row_count=x.shape[0]
    J_wb=0 
    J_wb+=(y*(np.log(compute_logistic(x,w,b)))+((1-y)*(np.log(1-compute_logistic(x,w,b)))))
    print("Row_count:",row_count)
    return np.sum(J_wb)/(-row_count)

In [181]:
cost=compute_logistics_loss(x,y,w,b)
print("Cost :",cost)
#11.587969087943256

X: [[0.25905518 0.32779069 0.53856307 0.43586175 0.34719479 0.46032131]
 [0.41884025 0.04570232 0.64506201 0.94240861 0.28457244 0.22646675]
 [0.5775232  0.13003756 0.93154279 0.24364431 0.44417751 0.66790269]]
w: [ 0 79 -3 -2 -1 98]
b: 0.7600000000000504
Compute_linear : [68.93234497 22.45964878 72.76133651]
Math : [1.15627984e-30 1.76156417e-10 2.51277185e-32]
math+1: [1. 1. 1.]
Final : [1. 1. 1.]
X: [[0.25905518 0.32779069 0.53856307 0.43586175 0.34719479 0.46032131]
 [0.41884025 0.04570232 0.64506201 0.94240861 0.28457244 0.22646675]
 [0.5775232  0.13003756 0.93154279 0.24364431 0.44417751 0.66790269]]
w: [ 0 79 -3 -2 -1 98]
b: 0.7600000000000504
Compute_linear : [68.93234497 22.45964878 72.76133651]
Math : [1.15627984e-30 1.76156417e-10 2.51277185e-32]
math+1: [1. 1. 1.]
Final : [1. 1. 1.]
Row_count: 3
Cost : inf


/var/folders/kq/3v19hhb53m9dfk3n1w8rgqbc0000gn/T/ipykernel_3372/2804212736.py:4: RuntimeWarning: divide by zero encountered in log
  J_wb+=(y*(np.log(compute_logistic(x,w,b)))+((1-y)*(np.log(1-compute_logistic(x,w,b)))))


In [183]:
def compute_dwj_jwb(w,y,b,j,x,m):
    return (np.sum(compute_logistic(x,w,b)-y*x[:,j]))/m

In [185]:
def compute_db_jwb(w,y,b,x,m):
    return (np.sum(compute_logistic(x,w,b)-y))/m

In [187]:
def compute_gradient(w,y,b,a,x):
    m=x.shape[0]
    b=b-(a*compute_db_jwb(w,y,b,x,m))
    for j in range(x.shape[1]):
        w[j]=w[j]-(a*compute_dwj_jwb(w,y,b,j,x,m))
    return w,b

In [214]:
def compute_gradient_descent_2(w,y,b,a,x):
    
    previous_err= 0
    new_err= -1
    while abs(new_err-previous_err)>=0.00000001:
        print("previous_err",previous_err)
        print("new_err",new_err)
        previous_err=new_err
        w,b=compute_gradient(w,y,b,a,x)
        new_err=compute_logistics_loss(x,y,w,b)
        print("New :",new_err)
    return b,w
        
        

In [216]:
print(x_train)

[[ 3.     22.      1.      1.      0.      7.25  ]
 [ 1.     38.      0.      1.      0.     71.2833]
 [ 3.     26.      0.      0.      0.      7.925 ]
 ...
 [ 1.     19.      0.      0.      0.     30.    ]
 [ 1.     26.      1.      0.      0.     30.    ]
 [ 3.     32.      1.      0.      0.      7.75  ]]


In [218]:
b,w=compute_gradient_descent_2(w,Y,b,a,x_train)
print("b :",b)
print("w :",w)

# print(compute_logistic(x,w,b),y,x[:,j])
#b : -0.0016423046999927604
# w : [-0.00222874 -0.00322001 -0.00261355 -0.00476759 -0.00294419 -0.00201518]
# Cost : 0.6919231783396347


previous_err 0
new_err -1
X: [[ 3.     22.      1.      1.      0.      7.25  ]
 [ 1.     38.      0.      1.      0.     71.2833]
 [ 3.     26.      0.      0.      0.      7.925 ]
 ...
 [ 1.     19.      0.      0.      0.     30.    ]
 [ 1.     26.      1.      0.      0.     30.    ]
 [ 3.     32.      1.      0.      0.      7.75  ]]
w: [  0 391 -23 -22 -21 470]
b: -16.199999999999953
Compute_linear : [ 11948.3    48322.951  13874.55   38603.8    17429.3    45450.175
  10561.05   15731.451  19569.076   9353.8    35140.3    11564.3
  29782.05    9149.274  29008.8    14322.55   20542.8    25865.8
  19364.8     9622.524  27593.8    12930.05   29466.925 130891.8
  28629.576  30701.8    49507.076  40800.8    11955.3    15437.8
  10719.399  20055.05   20388.8    20635.024  11116.024  15365.8
  21241.925  11837.8    55183.524  23520.8    54485.024  13129.8
  14502.024  14917.3    26152.8    11960.524  52441.8    56767.05
  14529.8    16257.8    11224.201  10225.55   14154.175  17407.8
  

/var/folders/kq/3v19hhb53m9dfk3n1w8rgqbc0000gn/T/ipykernel_3372/2804212736.py:4: RuntimeWarning: divide by zero encountered in log
  J_wb+=(y*(np.log(compute_logistic(x,w,b)))+((1-y)*(np.log(1-compute_logistic(x,w,b)))))
/var/folders/kq/3v19hhb53m9dfk3n1w8rgqbc0000gn/T/ipykernel_3372/2804212736.py:4: RuntimeWarning: invalid value encountered in multiply
  J_wb+=(y*(np.log(compute_logistic(x,w,b)))+((1-y)*(np.log(1-compute_logistic(x,w,b)))))


In [220]:
#dwj_jwb= sigma_1_m((f_wb(x_i)-y(i))x_ij)
#w_j=w_j-alpha*dwj_jwb

In [222]:
x=np.random.rand(3,6)
w=initialize_weights(6)
b=random.randint(1,10)
y=np.array([0,1,0])
a=0.01

In [76]:
def compute_differential_para(x,y,w,b):
    row_count,column_count=x.shape
    dj_db=0
    dj_dw=np.zeros((x.shape[1],))
    
    for row in range(row_count):
        err=(compute_logistic(x[row],w,b)-y[row])
        dj_db+=err
        for column in range(column_count):
            dj_dw[column]+=(err*x[row,column])
    dj_db/=row_count
    dj_dw/=row_count
    return dj_db,dj_dw

In [78]:
dj_db,dj_dw=compute_differential_para(x,y,w,b)
print(dj_db,dj_dw)
#0.666666556330921 1.759265107992439

7.26963509191677e-08
6.53354792147667e-06
1.243793050383443e-07
0.66666442313971 [0.24916921 0.35340119 0.5300284  0.43996963 0.37264659 0.11100163]


In [127]:
def compute_gradient_descent(x,y,w,b,a):
    row_count,column_count=x.shape
    dj_db,dj_dw= compute_differential_para(x,y,w,b)
    alpha=a
    for count in range(1000000):
        w=w-(alpha*dj_dw)
        b=b-(alpha*dj_db)
    return b,w

In [129]:
b,w=compute_gradient_descent(x_train,y_train,w,b,a)
print("b :",b)
print("w :",w)
cost=compute_logistics_loss(x_train,y_train,w,b)
print("Cost :",cost)

KeyError: 0